In [57]:
import numpy as np
import pandas as pd

In [2]:
A = np.array(np.arange(16)).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
A[1:3:2]


array([[4, 5, 6, 7]])

In [45]:
A[:, 0:4:3]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

In [49]:
A.shape[0]

4

In [47]:
keep_rows = np.zeros(A.shape[0], bool)
keep_rows

array([False, False, False, False])

In [52]:
keep_rows[[1, 3]] = True
np.all(keep_rows == np.array([0, 1, 0, 1]))

True

In [55]:
A[np.array([0, 1, 0, 1])]

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [53]:
A[keep_rows]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [58]:
rng = np.random.default_rng(1)
A = rng.standard_normal((127, 5))
M = rng.choice([0, np.nan], p=[0.8,0.2], size=A.shape)
A += M
D = pd.DataFrame(A, columns=['food',
'bar',
'pickle',
'snack',
'popcorn'])
D[:3]

food       bar    pickle     snack   popcorn
0  0.345584  0.821618  0.330437 -1.303157       NaN
1       NaN -0.536953  0.581118  0.364572  0.294132
2       NaN  0.546713       NaN -0.162910 -0.482119

In [61]:
pd.DataFrame(A)

0         1         2         3         4
0    0.345584  0.821618  0.330437 -1.303157       NaN
1         NaN -0.536953  0.581118  0.364572  0.294132
2         NaN  0.546713       NaN -0.162910 -0.482119
3    0.598846       NaN       NaN -0.781908       NaN
4    0.008142 -0.275603  1.294064       NaN -2.711162
..        ...       ...       ...       ...       ...
122       NaN -1.421741  0.011192       NaN  0.128476
123  0.887647 -0.243649  0.730347  0.720844       NaN
124  1.716248  0.778838       NaN -0.680824 -0.845306
125  0.475867 -0.323722  2.729167  1.842448 -0.214524
126 -0.329131  1.690177 -1.883360 -0.451551  0.950757

[127 rows x 5 columns]